const {app,BrowserWindow,ipcMain,shell}=require("electron");
const path=require("path"),fs=require("fs"),crypto=require("crypto");
const {TronWeb}=require("tronweb");
const HOST="https://api.trongrid.io",USDT="TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t";
let vault=null,sessionPassword=null;
const tron=()=>new TronWeb({fullHost:HOST});
const vaultPath=()=>path.join(app.getPath("userData"),"wallet.vault");
function normalizePk(x){x=String(x||"").trim().replace(/^0x/i,"");if(!/^[0-9a-fA-F]{64}$/.test(x))throw Error("Private key должен содержать 64 hex-символа.");return x}
function derive(p,s){return crypto.scryptSync(p,s,32,{N:16384,r:8,p:1})}
function encrypt(text,p){const s=crypto.randomBytes(16),iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",derive(p,s),iv),ct=Buffer.concat([c.update(text,"utf8"),c.final()]);return{s:s.toString("base64"),i:iv.toString("base64"),t:c.getAuthTag().toString("base64"),c:ct.toString("base64")}}
function decrypt(v,p){const d=crypto.createDecipheriv("aes-256-gcm",derive(p,Buffer.from(v.s,"base64")),Buffer.from(v.i,"base64"));d.setAuthTag(Buffer.from(v.t,"base64"));return Buffer.concat([d.update(Buffer.from(v.c,"base64")),d.final()]).toString()}
function save(){if(!vault||!sessionPassword)throw Error("Vault заблокирован.");fs.writeFileSync(vaultPath(),JSON.stringify(encrypt(JSON.stringify(vault),sessionPassword)))}
function active(){if(!vault)throw Error("Vault заблокирован.");const w=vault.wallets.find(x=>x.id===vault.activeWalletId);if(!w)throw Error("Активный кошелёк не найден.");return w}
function activePk(){return normalizePk(decrypt(active().key,sessionPassword))}
function publicVault(){return{activeWalletId:vault.activeWalletId,wallets:vault.wallets.map(w=>({id:w.id,name:w.name,address:w.address}))}}
function units(x){x=String(x).trim();if(!/^\d+(\.\d+)?$/.test(x))throw Error("Некорректная сумма.");let[a,b=""]=x.split(".");if(b.length>6)throw Error("Максимум 6 знаков после запятой.");const n=BigInt(a)*1000000n+BigInt((b+"000000").slice(0,6));if(n<=0n)throw Error("Сумма должна быть больше нуля.");return n}
function decodeMessage(v){if(!v)return"";try{if(typeof v==="string"&&/^[0-9a-fA-F]+$/.test(v)&&v.length%2===0)return Buffer.from(v,"hex").toString("utf8")}catch{}return String(v)}
function tronError(r){const code=r?.code||r?.result?.code||"TRON_ERROR",m=r?.message||r?.result?.message;return code+(m?": "+decodeMessage(m):"")}
async function getUsdt(t,a){const r=await t.transactionBuilder.triggerConstantContract(USDT,"balanceOf(address)",{},[{type:"address",value:a}],a);if(!r?.result?.result)throw Error("USDT balance: "+tronError(r));return r.constant_result?.[0]?BigInt("0x"+r.constant_result[0]):0n}
ipcMain.handle("exists",()=>fs.existsSync(vaultPath()));
ipcMain.handle("create",(_,pk,p,name)=>{if(!p||p.length<10)throw Error("Пароль минимум 10 символов.");pk=normalizePk(pk);sessionPassword=p;const id=crypto.randomUUID(),address=tron().address.fromPrivateKey(pk);vault={version:2,activeWalletId:id,wallets:[{id,name:String(name||"Основной").trim()||"Основной",address,key:encrypt(pk,p)}]};save();return publicVault()});
ipcMain.handle("unlock",(_,p)=>{try{const old=JSON.parse(fs.readFileSync(vaultPath(),"utf8")),plain=decrypt(old,p);sessionPassword=p;if(/^[0-9a-fA-F]{64}$/.test(plain)){const pk=normalizePk(plain),id=crypto.randomUUID(),address=tron().address.fromPrivateKey(pk);vault={version:2,activeWalletId:id,wallets:[{id,name:"Основной",address,key:encrypt(pk,p)}]};save()}else{vault=JSON.parse(plain);if(vault.version!==2||!Array.isArray(vault.wallets))throw Error()}return publicVault()}catch{vault=null;sessionPassword=null;throw Error("Неверный пароль или повреждён vault.")}});
ipcMain.handle("lock",()=>{vault=null;sessionPassword=null;return true});
ipcMain.handle("list",()=>publicVault());
ipcMain.handle("add",(_,pk,name)=>{pk=normalizePk(pk);const address=tron().address.fromPrivateKey(pk);if(vault.wallets.some(w=>w.address===address))throw Error("Этот кошелёк уже добавлен.");const id=crypto.randomUUID();vault.wallets.push({id,name:String(name||("Wallet "+(vault.wallets.length+1))).trim(),address,key:encrypt(pk,sessionPassword)});vault.activeWalletId=id;save();return publicVault()});
ipcMain.handle("select",(_,id)=>{if(!vault.wallets.some(w=>w.id===id))throw Error("Кошелёк не найден.");vault.activeWalletId=id;save();return publicVault()});
ipcMain.handle("rename",(_,id,name)=>{const w=vault.wallets.find(x=>x.id===id);name=String(name||"").trim();if(!w||!name)throw Error("Некорректное имя.");w.name=name;save();return publicVault()});
ipcMain.handle("remove",(_,id)=>{if(vault.wallets.length<=1)throw Error("Нельзя удалить единственный кошелёк.");vault.wallets=vault.wallets.filter(w=>w.id!==id);if(vault.activeWalletId===id)vault.activeWalletId=vault.wallets[0].id;save();return publicVault()});
ipcMain.handle("info",async()=>{const t=tron(),w=active(),a=w.address;const [sun,u,r]=await Promise.all([t.trx.getBalance(a),getUsdt(t,a),t.trx.getAccountResources(a)]);const fl=Number(r.freeNetLimit||0),fu=Number(r.freeNetUsed||0),nl=Number(r.NetLimit||0),nu=Number(r.NetUsed||0),el=Number(r.EnergyLimit||0),eu=Number(r.EnergyUsed||0);return{name:w.name,address:a,trx:(Number(sun)/1e6).toFixed(6),usdt:`${u/1000000n}.${(u%1000000n).toString().padStart(6,"0")}`,energyAvailable:Math.max(0,el-eu),energyLimit:el,bandwidthAvailable:Math.max(0,fl-fu)+Math.max(0,nl-nu),bandwidthLimit:fl+nl}});
ipcMain.handle("trx",async(_,to,amount)=>{const t=tron(),w=active();if(!t.isAddress(to))throw Error("Некорректный TRON-адрес.");const n=units(amount);if(n>BigInt(Number.MAX_SAFE_INTEGER))throw Error("Сумма слишком велика.");const bal=BigInt(await t.trx.getBalance(w.address));if(bal<n)throw Error("Недостаточно TRX.");const tx=await t.transactionBuilder.sendTrx(to,Number(n),w.address),signed=await t.trx.sign(tx,activePk()),r=await t.trx.sendRawTransaction(signed);if(!r?.result)throw Error(tronError(r));return r.txid||signed.txID});
ipcMain.handle("usdt",async(_,to,amount)=>{const t=tron(),w=active();if(!t.isAddress(to))throw Error("Некорректный TRON-адрес.");const n=units(amount),b=await t.transactionBuilder.triggerSmartContract(USDT,"transfer(address,uint256)",{feeLimit:100000000},[{type:"address",value:to},{type:"uint256",value:n.toString()}],w.address);if(!b?.result?.result||!b.transaction)throw Error(tronError(b));const signed=await t.trx.sign(b.transaction,activePk()),r=await t.trx.sendRawTransaction(signed);if(!r?.result)throw Error(tronError(r));return r.txid||signed.txID});
ipcMain.handle("open",(_,tx)=>shell.openExternal("https://tronscan.org/#/transaction/"+encodeURIComponent(tx)));
app.whenReady().then(()=>{const w=new BrowserWindow({width:1050,height:760,minWidth:850,minHeight:650,webPreferences:{preload:path.join(__dirname,"preload.js"),contextIsolation:true,nodeIntegration:false,sandbox:true}});w.removeMenu();w.loadFile(path.join(__dirname,"index.html"))});
app.on("window-all-closed",()=>{vault=null;sessionPassword=null;if(process.platform!=="darwin")app.quit()});
