let token="TRX",state=null;const $=id=>document.getElementById(id);
function status(x){const s=$("status");s.textContent=x;s.style.display="block";setTimeout(()=>s.style.display="none",6000)}
function fmt(x){return Number(x||0).toLocaleString("ru-RU")}
async function renderWallets(){state=await api.list();$("walletList").innerHTML="";for(const w of state.wallets){const d=document.createElement("div");d.className="wallet "+(w.id===state.activeWalletId?"active":"");d.innerHTML=`<b>${w.name}</b><small>${w.address}</small><button class="rename">Имя</button><button class="remove">Удалить</button>`;d.onclick=async e=>{try{if(e.target.className==="rename"){e.stopPropagation();const n=prompt("Новое имя:",w.name);if(n)await api.rename(w.id,n)}else if(e.target.className==="remove"){e.stopPropagation();if(confirm("Удалить кошелёк из программы? Средства в сети не удаляются."))await api.remove(w.id)}else await api.select(w.id);await renderWallets();await loadInfo()}catch(err){status(err.message)}};$("walletList").appendChild(d)}}
async function loadInfo(){try{const x=await api.info();$("activeName").textContent=x.name;$("address").textContent=x.address;$("trx").textContent=x.trx;$("usdt").textContent=x.usdt;$("energy").textContent=fmt(x.energyAvailable);$("energyLimit").textContent="лимит: "+fmt(x.energyLimit);$("bandwidth").textContent=fmt(x.bandwidthAvailable);$("bandwidthLimit").textContent="лимит: "+fmt(x.bandwidthLimit)}catch(e){status(e.message)}}
async function init(){const exists=await api.exists();$("authTitle").textContent=exists?"Разблокировать vault":"Создать vault";$("newFields").classList.toggle("hidden",exists)}
$("authBtn").onclick=async()=>{try{const exists=await api.exists();if(exists)await api.unlock($("password").value);else await api.create($("firstPk").value,$("password").value,$("firstName").value);$("auth").classList.add("hidden");$("app").classList.remove("hidden");$("lock").classList.remove("hidden");$("password").value="";$("firstPk").value="";await renderWallets();await loadInfo()}catch(e){status(e.message)}};
$("lock").onclick=async()=>{await api.lock();$("app").classList.add("hidden");$("lock").classList.add("hidden");$("auth").classList.remove("hidden");init()};
$("refresh").onclick=loadInfo;$("addBtn").onclick=()=>$("addDialog").showModal();$("cancelAdd").onclick=()=>$("addDialog").close();
$("confirmAdd").onclick=async()=>{try{await api.add($("addPk").value,$("addName").value);$("addPk").value="";$("addName").value="";$("addDialog").close();await renderWallets();await loadInfo()}catch(e){status(e.message)}};
document.querySelectorAll(".token").forEach(b=>b.onclick=()=>{document.querySelectorAll(".token").forEach(x=>x.classList.remove("active"));b.classList.add("active");token=b.dataset.token;$("resourceHint").textContent=token==="TRX"?"TRX использует Bandwidth.":"USDT использует Energy; при нехватке ресурсов может расходоваться TRX."});
$("send").onclick=async()=>{const to=$("to").value.trim(),amount=$("amount").value.trim();const w=state.wallets.find(x=>x.id===state.activeWalletId);if(!confirm(`MAINNET\nКошелёк: ${w?.name||""}\nОтправить ${amount} ${token}\nна ${to}?`))return;try{const tx=token==="TRX"?await api.trx(to,amount):await api.usdt(to,amount);$("result").classList.remove("hidden");$("result").innerHTML=`<b>Транзакция отправлена</b><br><code>${tx}</code><br><button id="scan">TRONSCAN</button>`;$("scan").onclick=()=>api.open(tx);await loadInfo()}catch(e){status(e.message)}};
init();
